version: '3.8'

services:

  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: tooldb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sneham@2004
    ports:
      - "5432:5432"

  app:
    image: demo-app
    container_name: demo-container
    ports:
      - "8082:8082"
    depends_on:
      - postgres